#!/bin/bash

HERE="$(dirname "$(readlink -f "${0}")")"

export PYTHONHOME="${HERE}/usr"
export PYTHONPATH="${HERE}/usr/lib/python3.11:${HERE}/usr/lib/python3.11/site-packages"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PATH="${HERE}/usr/bin:${PATH}"

cd "${HERE}"

exec "${HERE}/usr/bin/python3" "${HERE}/backend/app.py" "$@"
